// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: centerplugin/v1/center_plugin.proto

package centerpluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CenterPlugin_GetInfo_FullMethodName            = "/relayward.centerplugin.v1.CenterPlugin/GetInfo"
	CenterPlugin_Activate_FullMethodName           = "/relayward.centerplugin.v1.CenterPlugin/Activate"
	CenterPlugin_GetStatus_FullMethodName          = "/relayward.centerplugin.v1.CenterPlugin/GetStatus"
	CenterPlugin_InvokeUI_FullMethodName           = "/relayward.centerplugin.v1.CenterPlugin/InvokeUI"
	CenterPlugin_RenderSubscription_FullMethodName = "/relayward.centerplugin.v1.CenterPlugin/RenderSubscription"
)

// CenterPluginClient is the client API for CenterPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CenterPluginClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*Activated, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	InvokeUI(ctx context.Context, in *InvokeUIRequest, opts ...grpc.CallOption) (*InvokeUIResponse, error)
	RenderSubscription(ctx context.Context, in *RenderSubscriptionRequest, opts ...grpc.CallOption) (*RenderSubscriptionResponse, error)
}

type centerPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewCenterPluginClient(cc grpc.ClientConnInterface) CenterPluginClient {
	return &centerPluginClient{cc}
}

func (c *centerPluginClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, CenterPlugin_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerPluginClient) Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*Activated, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Activated)
	err := c.cc.Invoke(ctx, CenterPlugin_Activate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerPluginClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, CenterPlugin_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerPluginClient) InvokeUI(ctx context.Context, in *InvokeUIRequest, opts ...grpc.CallOption) (*InvokeUIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeUIResponse)
	err := c.cc.Invoke(ctx, CenterPlugin_InvokeUI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerPluginClient) RenderSubscription(ctx context.Context, in *RenderSubscriptionRequest, opts ...grpc.CallOption) (*RenderSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderSubscriptionResponse)
	err := c.cc.Invoke(ctx, CenterPlugin_RenderSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CenterPluginServer is the server API for CenterPlugin service.
// All implementations must embed UnimplementedCenterPluginServer
// for forward compatibility.
type CenterPluginServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	Activate(context.Context, *ActivateRequest) (*Activated, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	InvokeUI(context.Context, *InvokeUIRequest) (*InvokeUIResponse, error)
	RenderSubscription(context.Context, *RenderSubscriptionRequest) (*RenderSubscriptionResponse, error)
	mustEmbedUnimplementedCenterPluginServer()
}

// UnimplementedCenterPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCenterPluginServer struct{}

func (UnimplementedCenterPluginServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedCenterPluginServer) Activate(context.Context, *ActivateRequest) (*Activated, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Activate not implemented")
}
func (UnimplementedCenterPluginServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedCenterPluginServer) InvokeUI(context.Context, *InvokeUIRequest) (*InvokeUIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeUI not implemented")
}
func (UnimplementedCenterPluginServer) RenderSubscription(context.Context, *RenderSubscriptionRequest) (*RenderSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenderSubscription not implemented")
}
func (UnimplementedCenterPluginServer) mustEmbedUnimplementedCenterPluginServer() {}
func (UnimplementedCenterPluginServer) testEmbeddedByValue()                      {}

// UnsafeCenterPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CenterPluginServer will
// result in compilation errors.
type UnsafeCenterPluginServer interface {
	mustEmbedUnimplementedCenterPluginServer()
}

func RegisterCenterPluginServer(s grpc.ServiceRegistrar, srv CenterPluginServer) {
	// If the following call pancis, it indicates UnimplementedCenterPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CenterPlugin_ServiceDesc, srv)
}

func _CenterPlugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterPluginServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterPlugin_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterPluginServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterPlugin_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterPluginServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterPlugin_Activate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterPluginServer).Activate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterPlugin_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterPluginServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterPlugin_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterPluginServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterPlugin_InvokeUI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeUIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterPluginServer).InvokeUI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterPlugin_InvokeUI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterPluginServer).InvokeUI(ctx, req.(*InvokeUIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterPlugin_RenderSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterPluginServer).RenderSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterPlugin_RenderSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterPluginServer).RenderSubscription(ctx, req.(*RenderSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CenterPlugin_ServiceDesc is the grpc.ServiceDesc for CenterPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CenterPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relayward.centerplugin.v1.CenterPlugin",
	HandlerType: (*CenterPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _CenterPlugin_GetInfo_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _CenterPlugin_Activate_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _CenterPlugin_GetStatus_Handler,
		},
		{
			MethodName: "InvokeUI",
			Handler:    _CenterPlugin_InvokeUI_Handler,
		},
		{
			MethodName: "RenderSubscription",
			Handler:    _CenterPlugin_RenderSubscription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "centerplugin/v1/center_plugin.proto",
}

const (
	PluginHost_ListNodes_FullMethodName       = "/relayward.centerplugin.v1.PluginHost/ListNodes"
	PluginHost_ReplaceServices_FullMethodName = "/relayward.centerplugin.v1.PluginHost/ReplaceServices"
)

// PluginHostClient is the client API for PluginHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginHostClient interface {
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	ReplaceServices(ctx context.Context, in *ReplaceServicesRequest, opts ...grpc.CallOption) (*ServicesReplaced, error)
}

type pluginHostClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginHostClient(cc grpc.ClientConnInterface) PluginHostClient {
	return &pluginHostClient{cc}
}

func (c *pluginHostClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, PluginHost_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) ReplaceServices(ctx context.Context, in *ReplaceServicesRequest, opts ...grpc.CallOption) (*ServicesReplaced, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServicesReplaced)
	err := c.cc.Invoke(ctx, PluginHost_ReplaceServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginHostServer is the server API for PluginHost service.
// All implementations must embed UnimplementedPluginHostServer
// for forward compatibility.
type PluginHostServer interface {
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	ReplaceServices(context.Context, *ReplaceServicesRequest) (*ServicesReplaced, error)
	mustEmbedUnimplementedPluginHostServer()
}

// UnimplementedPluginHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginHostServer struct{}

func (UnimplementedPluginHostServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedPluginHostServer) ReplaceServices(context.Context, *ReplaceServicesRequest) (*ServicesReplaced, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceServices not implemented")
}
func (UnimplementedPluginHostServer) mustEmbedUnimplementedPluginHostServer() {}
func (UnimplementedPluginHostServer) testEmbeddedByValue()                    {}

// UnsafePluginHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginHostServer will
// result in compilation errors.
type UnsafePluginHostServer interface {
	mustEmbedUnimplementedPluginHostServer()
}

func RegisterPluginHostServer(s grpc.ServiceRegistrar, srv PluginHostServer) {
	// If the following call pancis, it indicates UnimplementedPluginHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginHost_ServiceDesc, srv)
}

func _PluginHost_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_ReplaceServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).ReplaceServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_ReplaceServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).ReplaceServices(ctx, req.(*ReplaceServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginHost_ServiceDesc is the grpc.ServiceDesc for PluginHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relayward.centerplugin.v1.PluginHost",
	HandlerType: (*PluginHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNodes",
			Handler:    _PluginHost_ListNodes_Handler,
		},
		{
			MethodName: "ReplaceServices",
			Handler:    _PluginHost_ReplaceServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "centerplugin/v1/center_plugin.proto",
}
