// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: centerplugin/v1/center_plugin.proto

package centerpluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Health int32

const (
	Health_HEALTH_UNSPECIFIED Health = 0
	Health_HEALTH_STARTING    Health = 1
	Health_HEALTH_HEALTHY     Health = 2
	Health_HEALTH_UNHEALTHY   Health = 3
)

// Enum value maps for Health.
var (
	Health_name = map[int32]string{
		0: "HEALTH_UNSPECIFIED",
		1: "HEALTH_STARTING",
		2: "HEALTH_HEALTHY",
		3: "HEALTH_UNHEALTHY",
	}
	Health_value = map[string]int32{
		"HEALTH_UNSPECIFIED": 0,
		"HEALTH_STARTING":    1,
		"HEALTH_HEALTHY":     2,
		"HEALTH_UNHEALTHY":   3,
	}
)

func (x Health) Enum() *Health {
	p := new(Health)
	*p = x
	return p
}

func (x Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Health) Descriptor() protoreflect.EnumDescriptor {
	return file_centerplugin_v1_center_plugin_proto_enumTypes[0].Descriptor()
}

func (Health) Type() protoreflect.EnumType {
	return &file_centerplugin_v1_center_plugin_proto_enumTypes[0]
}

func (x Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Health.Descriptor instead.
func (Health) EnumDescriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetInfoResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ActivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ActivateRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type Activated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activated) Reset() {
	*x = Activated{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activated) ProtoMessage() {}

func (x *Activated) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activated.ProtoReflect.Descriptor instead.
func (*Activated) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Activated) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{4}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        Health                 `protobuf:"varint,1,opt,name=health,proto3,enum=relayward.centerplugin.v1.Health" json:"health,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetHealth() Health {
	if x != nil {
		return x.Health
	}
	return Health_HEALTH_UNSPECIFIED
}

func (x *GetStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InvokeUIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Json          []byte                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeUIRequest) Reset() {
	*x = InvokeUIRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeUIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeUIRequest) ProtoMessage() {}

func (x *InvokeUIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeUIRequest.ProtoReflect.Descriptor instead.
func (*InvokeUIRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *InvokeUIRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeUIRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type InvokeUIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeUIResponse) Reset() {
	*x = InvokeUIResponse{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeUIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeUIResponse) ProtoMessage() {}

func (x *InvokeUIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeUIResponse.ProtoReflect.Descriptor instead.
func (*InvokeUIResponse) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeUIResponse) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{8}
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Connected     bool                   `protobuf:"varint,4,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Node) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_centerplugin_v1_center_plugin_proto protoreflect.FileDescriptor

const file_centerplugin_v1_center_plugin_proto_rawDesc = "" +
	"\n" +
	"#centerplugin/v1/center_plugin.proto\x12\x19relayward.centerplugin.v1\"\x10\n" +
	"\x0eGetInfoRequest\"i\n" +
	"\x0fGetInfoResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"3\n" +
	"\x0fActivateRequest\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\"-\n" +
	"\tActivated\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\"\x12\n" +
	"\x10GetStatusRequest\"h\n" +
	"\x11GetStatusResponse\x129\n" +
	"\x06health\x18\x01 \x01(\x0e2!.relayward.centerplugin.v1.HealthR\x06health\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x0fInvokeUIRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04json\x18\x02 \x01(\fR\x04json\"&\n" +
	"\x10InvokeUIResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"\x12\n" +
	"\x10ListNodesRequest\"b\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1c\n" +
	"\tconnected\x18\x04 \x01(\bR\tconnected\"J\n" +
	"\x11ListNodesResponse\x125\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1f.relayward.centerplugin.v1.NodeR\x05nodes*_\n" +
	"\x06Health\x12\x16\n" +
	"\x12HEALTH_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHEALTH_STARTING\x10\x01\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x02\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x032\x9b\x03\n" +
	"\fCenterPlugin\x12`\n" +
	"\aGetInfo\x12).relayward.centerplugin.v1.GetInfoRequest\x1a*.relayward.centerplugin.v1.GetInfoResponse\x12\\\n" +
	"\bActivate\x12*.relayward.centerplugin.v1.ActivateRequest\x1a$.relayward.centerplugin.v1.Activated\x12f\n" +
	"\tGetStatus\x12+.relayward.centerplugin.v1.GetStatusRequest\x1a,.relayward.centerplugin.v1.GetStatusResponse\x12c\n" +
	"\bInvokeUI\x12*.relayward.centerplugin.v1.InvokeUIRequest\x1a+.relayward.centerplugin.v1.InvokeUIResponse2t\n" +
	"\n" +
	"PluginHost\x12f\n" +
	"\tListNodes\x12+.relayward.centerplugin.v1.ListNodesRequest\x1a,.relayward.centerplugin.v1.ListNodesResponseBCZAgithub.com/Relayward/relayward-sdk/centerplugin/v1;centerpluginv1b\x06proto3"

var (
	file_centerplugin_v1_center_plugin_proto_rawDescOnce sync.Once
	file_centerplugin_v1_center_plugin_proto_rawDescData []byte
)

func file_centerplugin_v1_center_plugin_proto_rawDescGZIP() []byte {
	file_centerplugin_v1_center_plugin_proto_rawDescOnce.Do(func() {
		file_centerplugin_v1_center_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_centerplugin_v1_center_plugin_proto_rawDesc), len(file_centerplugin_v1_center_plugin_proto_rawDesc)))
	})
	return file_centerplugin_v1_center_plugin_proto_rawDescData
}

var file_centerplugin_v1_center_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_centerplugin_v1_center_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_centerplugin_v1_center_plugin_proto_goTypes = []any{
	(Health)(0),               // 0: relayward.centerplugin.v1.Health
	(*GetInfoRequest)(nil),    // 1: relayward.centerplugin.v1.GetInfoRequest
	(*GetInfoResponse)(nil),   // 2: relayward.centerplugin.v1.GetInfoResponse
	(*ActivateRequest)(nil),   // 3: relayward.centerplugin.v1.ActivateRequest
	(*Activated)(nil),         // 4: relayward.centerplugin.v1.Activated
	(*GetStatusRequest)(nil),  // 5: relayward.centerplugin.v1.GetStatusRequest
	(*GetStatusResponse)(nil), // 6: relayward.centerplugin.v1.GetStatusResponse
	(*InvokeUIRequest)(nil),   // 7: relayward.centerplugin.v1.InvokeUIRequest
	(*InvokeUIResponse)(nil),  // 8: relayward.centerplugin.v1.InvokeUIResponse
	(*ListNodesRequest)(nil),  // 9: relayward.centerplugin.v1.ListNodesRequest
	(*Node)(nil),              // 10: relayward.centerplugin.v1.Node
	(*ListNodesResponse)(nil), // 11: relayward.centerplugin.v1.ListNodesResponse
}
var file_centerplugin_v1_center_plugin_proto_depIdxs = []int32{
	0,  // 0: relayward.centerplugin.v1.GetStatusResponse.health:type_name -> relayward.centerplugin.v1.Health
	10, // 1: relayward.centerplugin.v1.ListNodesResponse.nodes:type_name -> relayward.centerplugin.v1.Node
	1,  // 2: relayward.centerplugin.v1.CenterPlugin.GetInfo:input_type -> relayward.centerplugin.v1.GetInfoRequest
	3,  // 3: relayward.centerplugin.v1.CenterPlugin.Activate:input_type -> relayward.centerplugin.v1.ActivateRequest
	5,  // 4: relayward.centerplugin.v1.CenterPlugin.GetStatus:input_type -> relayward.centerplugin.v1.GetStatusRequest
	7,  // 5: relayward.centerplugin.v1.CenterPlugin.InvokeUI:input_type -> relayward.centerplugin.v1.InvokeUIRequest
	9,  // 6: relayward.centerplugin.v1.PluginHost.ListNodes:input_type -> relayward.centerplugin.v1.ListNodesRequest
	2,  // 7: relayward.centerplugin.v1.CenterPlugin.GetInfo:output_type -> relayward.centerplugin.v1.GetInfoResponse
	4,  // 8: relayward.centerplugin.v1.CenterPlugin.Activate:output_type -> relayward.centerplugin.v1.Activated
	6,  // 9: relayward.centerplugin.v1.CenterPlugin.GetStatus:output_type -> relayward.centerplugin.v1.GetStatusResponse
	8,  // 10: relayward.centerplugin.v1.CenterPlugin.InvokeUI:output_type -> relayward.centerplugin.v1.InvokeUIResponse
	11, // 11: relayward.centerplugin.v1.PluginHost.ListNodes:output_type -> relayward.centerplugin.v1.ListNodesResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_centerplugin_v1_center_plugin_proto_init() }
func file_centerplugin_v1_center_plugin_proto_init() {
	if File_centerplugin_v1_center_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_centerplugin_v1_center_plugin_proto_rawDesc), len(file_centerplugin_v1_center_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_centerplugin_v1_center_plugin_proto_goTypes,
		DependencyIndexes: file_centerplugin_v1_center_plugin_proto_depIdxs,
		EnumInfos:         file_centerplugin_v1_center_plugin_proto_enumTypes,
		MessageInfos:      file_centerplugin_v1_center_plugin_proto_msgTypes,
	}.Build()
	File_centerplugin_v1_center_plugin_proto = out.File
	file_centerplugin_v1_center_plugin_proto_goTypes = nil
	file_centerplugin_v1_center_plugin_proto_depIdxs = nil
}
