// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: centerplugin/v1/center_plugin.proto

package centerpluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Health int32

const (
	Health_HEALTH_UNSPECIFIED Health = 0
	Health_HEALTH_STARTING    Health = 1
	Health_HEALTH_HEALTHY     Health = 2
	Health_HEALTH_UNHEALTHY   Health = 3
)

// Enum value maps for Health.
var (
	Health_name = map[int32]string{
		0: "HEALTH_UNSPECIFIED",
		1: "HEALTH_STARTING",
		2: "HEALTH_HEALTHY",
		3: "HEALTH_UNHEALTHY",
	}
	Health_value = map[string]int32{
		"HEALTH_UNSPECIFIED": 0,
		"HEALTH_STARTING":    1,
		"HEALTH_HEALTHY":     2,
		"HEALTH_UNHEALTHY":   3,
	}
)

func (x Health) Enum() *Health {
	p := new(Health)
	*p = x
	return p
}

func (x Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Health) Descriptor() protoreflect.EnumDescriptor {
	return file_centerplugin_v1_center_plugin_proto_enumTypes[0].Descriptor()
}

func (Health) Type() protoreflect.EnumType {
	return &file_centerplugin_v1_center_plugin_proto_enumTypes[0]
}

func (x Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Health.Descriptor instead.
func (Health) EnumDescriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetInfoResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ActivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ActivateRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type Activated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activated) Reset() {
	*x = Activated{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activated) ProtoMessage() {}

func (x *Activated) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activated.ProtoReflect.Descriptor instead.
func (*Activated) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Activated) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{4}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        Health                 `protobuf:"varint,1,opt,name=health,proto3,enum=relayward.centerplugin.v1.Health" json:"health,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetHealth() Health {
	if x != nil {
		return x.Health
	}
	return Health_HEALTH_UNSPECIFIED
}

func (x *GetStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InvokeUIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Json          []byte                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeUIRequest) Reset() {
	*x = InvokeUIRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeUIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeUIRequest) ProtoMessage() {}

func (x *InvokeUIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeUIRequest.ProtoReflect.Descriptor instead.
func (*InvokeUIRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *InvokeUIRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeUIRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type InvokeUIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeUIResponse) Reset() {
	*x = InvokeUIResponse{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeUIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeUIResponse) ProtoMessage() {}

func (x *InvokeUIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeUIResponse.ProtoReflect.Descriptor instead.
func (*InvokeUIResponse) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeUIResponse) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{8}
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Connected     bool                   `protobuf:"varint,4,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Node) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ReplaceServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Services      []*PluginService       `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceServicesRequest) Reset() {
	*x = ReplaceServicesRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceServicesRequest) ProtoMessage() {}

func (x *ReplaceServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceServicesRequest.ProtoReflect.Descriptor instead.
func (*ReplaceServicesRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ReplaceServicesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReplaceServicesRequest) GetServices() []*PluginService {
	if x != nil {
		return x.Services
	}
	return nil
}

type PluginService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginService) Reset() {
	*x = PluginService{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginService) ProtoMessage() {}

func (x *PluginService) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginService.ProtoReflect.Descriptor instead.
func (*PluginService) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *PluginService) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginService) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PluginService) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PluginService) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ServicesReplaced struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceCount  uint32                 `protobuf:"varint,1,opt,name=service_count,json=serviceCount,proto3" json:"service_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicesReplaced) Reset() {
	*x = ServicesReplaced{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicesReplaced) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesReplaced) ProtoMessage() {}

func (x *ServicesReplaced) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesReplaced.ProtoReflect.Descriptor instead.
func (*ServicesReplaced) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ServicesReplaced) GetServiceCount() uint32 {
	if x != nil {
		return x.ServiceCount
	}
	return 0
}

type RenderSubscriptionRequest struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	AuthorizationId string                        `protobuf:"bytes,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	NodeId          string                        `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicAddress   string                        `protobuf:"bytes,3,opt,name=public_address,json=publicAddress,proto3" json:"public_address,omitempty"`
	Services        []*SubscriptionServiceBinding `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenderSubscriptionRequest) Reset() {
	*x = RenderSubscriptionRequest{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderSubscriptionRequest) ProtoMessage() {}

func (x *RenderSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*RenderSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *RenderSubscriptionRequest) GetAuthorizationId() string {
	if x != nil {
		return x.AuthorizationId
	}
	return ""
}

func (x *RenderSubscriptionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RenderSubscriptionRequest) GetPublicAddress() string {
	if x != nil {
		return x.PublicAddress
	}
	return ""
}

func (x *RenderSubscriptionRequest) GetServices() []*SubscriptionServiceBinding {
	if x != nil {
		return x.Services
	}
	return nil
}

type SubscriptionServiceBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionServiceBinding) Reset() {
	*x = SubscriptionServiceBinding{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionServiceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionServiceBinding) ProtoMessage() {}

func (x *SubscriptionServiceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionServiceBinding.ProtoReflect.Descriptor instead.
func (*SubscriptionServiceBinding) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *SubscriptionServiceBinding) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *SubscriptionServiceBinding) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type RenderSubscriptionResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Services      []*SubscriptionServiceContribution `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderSubscriptionResponse) Reset() {
	*x = RenderSubscriptionResponse{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderSubscriptionResponse) ProtoMessage() {}

func (x *RenderSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*RenderSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *RenderSubscriptionResponse) GetServices() []*SubscriptionServiceContribution {
	if x != nil {
		return x.Services
	}
	return nil
}

type SubscriptionServiceContribution struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServiceId            string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	DisplayName          string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Uris                 []string               `protobuf:"bytes,3,rep,name=uris,proto3" json:"uris,omitempty"`
	MihomoProxiesJson    [][]byte               `protobuf:"bytes,4,rep,name=mihomo_proxies_json,json=mihomoProxiesJson,proto3" json:"mihomo_proxies_json,omitempty"`
	SingBoxOutboundsJson [][]byte               `protobuf:"bytes,5,rep,name=sing_box_outbounds_json,json=singBoxOutboundsJson,proto3" json:"sing_box_outbounds_json,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubscriptionServiceContribution) Reset() {
	*x = SubscriptionServiceContribution{}
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionServiceContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionServiceContribution) ProtoMessage() {}

func (x *SubscriptionServiceContribution) ProtoReflect() protoreflect.Message {
	mi := &file_centerplugin_v1_center_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionServiceContribution.ProtoReflect.Descriptor instead.
func (*SubscriptionServiceContribution) Descriptor() ([]byte, []int) {
	return file_centerplugin_v1_center_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *SubscriptionServiceContribution) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *SubscriptionServiceContribution) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SubscriptionServiceContribution) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

func (x *SubscriptionServiceContribution) GetMihomoProxiesJson() [][]byte {
	if x != nil {
		return x.MihomoProxiesJson
	}
	return nil
}

func (x *SubscriptionServiceContribution) GetSingBoxOutboundsJson() [][]byte {
	if x != nil {
		return x.SingBoxOutboundsJson
	}
	return nil
}

var File_centerplugin_v1_center_plugin_proto protoreflect.FileDescriptor

const file_centerplugin_v1_center_plugin_proto_rawDesc = "" +
	"\n" +
	"#centerplugin/v1/center_plugin.proto\x12\x19relayward.centerplugin.v1\"\x10\n" +
	"\x0eGetInfoRequest\"i\n" +
	"\x0fGetInfoResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"3\n" +
	"\x0fActivateRequest\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\"-\n" +
	"\tActivated\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\"\x12\n" +
	"\x10GetStatusRequest\"h\n" +
	"\x11GetStatusResponse\x129\n" +
	"\x06health\x18\x01 \x01(\x0e2!.relayward.centerplugin.v1.HealthR\x06health\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x0fInvokeUIRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04json\x18\x02 \x01(\fR\x04json\"&\n" +
	"\x10InvokeUIResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"\x12\n" +
	"\x10ListNodesRequest\"b\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1c\n" +
	"\tconnected\x18\x04 \x01(\bR\tconnected\"J\n" +
	"\x11ListNodesResponse\x125\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1f.relayward.centerplugin.v1.NodeR\x05nodes\"w\n" +
	"\x16ReplaceServicesRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12D\n" +
	"\bservices\x18\x02 \x03(\v2(.relayward.centerplugin.v1.PluginServiceR\bservices\"\x80\x01\n" +
	"\rPluginService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"7\n" +
	"\x10ServicesReplaced\x12#\n" +
	"\rservice_count\x18\x01 \x01(\rR\fserviceCount\"\xd9\x01\n" +
	"\x19RenderSubscriptionRequest\x12)\n" +
	"\x10authorization_id\x18\x01 \x01(\tR\x0fauthorizationId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12%\n" +
	"\x0epublic_address\x18\x03 \x01(\tR\rpublicAddress\x12Q\n" +
	"\bservices\x18\x04 \x03(\v25.relayward.centerplugin.v1.SubscriptionServiceBindingR\bservices\"^\n" +
	"\x1aSubscriptionServiceBinding\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"t\n" +
	"\x1aRenderSubscriptionResponse\x12V\n" +
	"\bservices\x18\x01 \x03(\v2:.relayward.centerplugin.v1.SubscriptionServiceContributionR\bservices\"\xde\x01\n" +
	"\x1fSubscriptionServiceContribution\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04uris\x18\x03 \x03(\tR\x04uris\x12.\n" +
	"\x13mihomo_proxies_json\x18\x04 \x03(\fR\x11mihomoProxiesJson\x125\n" +
	"\x17sing_box_outbounds_json\x18\x05 \x03(\fR\x14singBoxOutboundsJson*_\n" +
	"\x06Health\x12\x16\n" +
	"\x12HEALTH_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHEALTH_STARTING\x10\x01\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x02\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x032\x9f\x04\n" +
	"\fCenterPlugin\x12`\n" +
	"\aGetInfo\x12).relayward.centerplugin.v1.GetInfoRequest\x1a*.relayward.centerplugin.v1.GetInfoResponse\x12\\\n" +
	"\bActivate\x12*.relayward.centerplugin.v1.ActivateRequest\x1a$.relayward.centerplugin.v1.Activated\x12f\n" +
	"\tGetStatus\x12+.relayward.centerplugin.v1.GetStatusRequest\x1a,.relayward.centerplugin.v1.GetStatusResponse\x12c\n" +
	"\bInvokeUI\x12*.relayward.centerplugin.v1.InvokeUIRequest\x1a+.relayward.centerplugin.v1.InvokeUIResponse\x12\x81\x01\n" +
	"\x12RenderSubscription\x124.relayward.centerplugin.v1.RenderSubscriptionRequest\x1a5.relayward.centerplugin.v1.RenderSubscriptionResponse2\xe7\x01\n" +
	"\n" +
	"PluginHost\x12f\n" +
	"\tListNodes\x12+.relayward.centerplugin.v1.ListNodesRequest\x1a,.relayward.centerplugin.v1.ListNodesResponse\x12q\n" +
	"\x0fReplaceServices\x121.relayward.centerplugin.v1.ReplaceServicesRequest\x1a+.relayward.centerplugin.v1.ServicesReplacedBCZAgithub.com/Relayward/relayward-sdk/centerplugin/v1;centerpluginv1b\x06proto3"

var (
	file_centerplugin_v1_center_plugin_proto_rawDescOnce sync.Once
	file_centerplugin_v1_center_plugin_proto_rawDescData []byte
)

func file_centerplugin_v1_center_plugin_proto_rawDescGZIP() []byte {
	file_centerplugin_v1_center_plugin_proto_rawDescOnce.Do(func() {
		file_centerplugin_v1_center_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_centerplugin_v1_center_plugin_proto_rawDesc), len(file_centerplugin_v1_center_plugin_proto_rawDesc)))
	})
	return file_centerplugin_v1_center_plugin_proto_rawDescData
}

var file_centerplugin_v1_center_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_centerplugin_v1_center_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_centerplugin_v1_center_plugin_proto_goTypes = []any{
	(Health)(0),                             // 0: relayward.centerplugin.v1.Health
	(*GetInfoRequest)(nil),                  // 1: relayward.centerplugin.v1.GetInfoRequest
	(*GetInfoResponse)(nil),                 // 2: relayward.centerplugin.v1.GetInfoResponse
	(*ActivateRequest)(nil),                 // 3: relayward.centerplugin.v1.ActivateRequest
	(*Activated)(nil),                       // 4: relayward.centerplugin.v1.Activated
	(*GetStatusRequest)(nil),                // 5: relayward.centerplugin.v1.GetStatusRequest
	(*GetStatusResponse)(nil),               // 6: relayward.centerplugin.v1.GetStatusResponse
	(*InvokeUIRequest)(nil),                 // 7: relayward.centerplugin.v1.InvokeUIRequest
	(*InvokeUIResponse)(nil),                // 8: relayward.centerplugin.v1.InvokeUIResponse
	(*ListNodesRequest)(nil),                // 9: relayward.centerplugin.v1.ListNodesRequest
	(*Node)(nil),                            // 10: relayward.centerplugin.v1.Node
	(*ListNodesResponse)(nil),               // 11: relayward.centerplugin.v1.ListNodesResponse
	(*ReplaceServicesRequest)(nil),          // 12: relayward.centerplugin.v1.ReplaceServicesRequest
	(*PluginService)(nil),                   // 13: relayward.centerplugin.v1.PluginService
	(*ServicesReplaced)(nil),                // 14: relayward.centerplugin.v1.ServicesReplaced
	(*RenderSubscriptionRequest)(nil),       // 15: relayward.centerplugin.v1.RenderSubscriptionRequest
	(*SubscriptionServiceBinding)(nil),      // 16: relayward.centerplugin.v1.SubscriptionServiceBinding
	(*RenderSubscriptionResponse)(nil),      // 17: relayward.centerplugin.v1.RenderSubscriptionResponse
	(*SubscriptionServiceContribution)(nil), // 18: relayward.centerplugin.v1.SubscriptionServiceContribution
}
var file_centerplugin_v1_center_plugin_proto_depIdxs = []int32{
	0,  // 0: relayward.centerplugin.v1.GetStatusResponse.health:type_name -> relayward.centerplugin.v1.Health
	10, // 1: relayward.centerplugin.v1.ListNodesResponse.nodes:type_name -> relayward.centerplugin.v1.Node
	13, // 2: relayward.centerplugin.v1.ReplaceServicesRequest.services:type_name -> relayward.centerplugin.v1.PluginService
	16, // 3: relayward.centerplugin.v1.RenderSubscriptionRequest.services:type_name -> relayward.centerplugin.v1.SubscriptionServiceBinding
	18, // 4: relayward.centerplugin.v1.RenderSubscriptionResponse.services:type_name -> relayward.centerplugin.v1.SubscriptionServiceContribution
	1,  // 5: relayward.centerplugin.v1.CenterPlugin.GetInfo:input_type -> relayward.centerplugin.v1.GetInfoRequest
	3,  // 6: relayward.centerplugin.v1.CenterPlugin.Activate:input_type -> relayward.centerplugin.v1.ActivateRequest
	5,  // 7: relayward.centerplugin.v1.CenterPlugin.GetStatus:input_type -> relayward.centerplugin.v1.GetStatusRequest
	7,  // 8: relayward.centerplugin.v1.CenterPlugin.InvokeUI:input_type -> relayward.centerplugin.v1.InvokeUIRequest
	15, // 9: relayward.centerplugin.v1.CenterPlugin.RenderSubscription:input_type -> relayward.centerplugin.v1.RenderSubscriptionRequest
	9,  // 10: relayward.centerplugin.v1.PluginHost.ListNodes:input_type -> relayward.centerplugin.v1.ListNodesRequest
	12, // 11: relayward.centerplugin.v1.PluginHost.ReplaceServices:input_type -> relayward.centerplugin.v1.ReplaceServicesRequest
	2,  // 12: relayward.centerplugin.v1.CenterPlugin.GetInfo:output_type -> relayward.centerplugin.v1.GetInfoResponse
	4,  // 13: relayward.centerplugin.v1.CenterPlugin.Activate:output_type -> relayward.centerplugin.v1.Activated
	6,  // 14: relayward.centerplugin.v1.CenterPlugin.GetStatus:output_type -> relayward.centerplugin.v1.GetStatusResponse
	8,  // 15: relayward.centerplugin.v1.CenterPlugin.InvokeUI:output_type -> relayward.centerplugin.v1.InvokeUIResponse
	17, // 16: relayward.centerplugin.v1.CenterPlugin.RenderSubscription:output_type -> relayward.centerplugin.v1.RenderSubscriptionResponse
	11, // 17: relayward.centerplugin.v1.PluginHost.ListNodes:output_type -> relayward.centerplugin.v1.ListNodesResponse
	14, // 18: relayward.centerplugin.v1.PluginHost.ReplaceServices:output_type -> relayward.centerplugin.v1.ServicesReplaced
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_centerplugin_v1_center_plugin_proto_init() }
func file_centerplugin_v1_center_plugin_proto_init() {
	if File_centerplugin_v1_center_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_centerplugin_v1_center_plugin_proto_rawDesc), len(file_centerplugin_v1_center_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_centerplugin_v1_center_plugin_proto_goTypes,
		DependencyIndexes: file_centerplugin_v1_center_plugin_proto_depIdxs,
		EnumInfos:         file_centerplugin_v1_center_plugin_proto_enumTypes,
		MessageInfos:      file_centerplugin_v1_center_plugin_proto_msgTypes,
	}.Build()
	File_centerplugin_v1_center_plugin_proto = out.File
	file_centerplugin_v1_center_plugin_proto_goTypes = nil
	file_centerplugin_v1_center_plugin_proto_depIdxs = nil
}
