// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: nodeplugin/v1/node_plugin.proto

package nodepluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Health int32

const (
	Health_HEALTH_UNSPECIFIED Health = 0
	Health_HEALTH_STARTING    Health = 1
	Health_HEALTH_HEALTHY     Health = 2
	Health_HEALTH_UNHEALTHY   Health = 3
)

// Enum value maps for Health.
var (
	Health_name = map[int32]string{
		0: "HEALTH_UNSPECIFIED",
		1: "HEALTH_STARTING",
		2: "HEALTH_HEALTHY",
		3: "HEALTH_UNHEALTHY",
	}
	Health_value = map[string]int32{
		"HEALTH_UNSPECIFIED": 0,
		"HEALTH_STARTING":    1,
		"HEALTH_HEALTHY":     2,
		"HEALTH_UNHEALTHY":   3,
	}
)

func (x Health) Enum() *Health {
	p := new(Health)
	*p = x
	return p
}

func (x Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Health) Descriptor() protoreflect.EnumDescriptor {
	return file_nodeplugin_v1_node_plugin_proto_enumTypes[0].Descriptor()
}

func (Health) Type() protoreflect.EnumType {
	return &file_nodeplugin_v1_node_plugin_proto_enumTypes[0]
}

func (x Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Health.Descriptor instead.
func (Health) EnumDescriptor() ([]byte, []int) {
	return file_nodeplugin_v1_node_plugin_proto_rawDescGZIP(), []int{0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_nodeplugin_v1_node_plugin_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_nodeplugin_v1_node_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetInfoResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Json          []byte                 `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationRequest) Reset() {
	*x = ConfigurationRequest{}
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationRequest) ProtoMessage() {}

func (x *ConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_nodeplugin_v1_node_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigurationRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ConfigurationRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ConfigurationRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type ConfigurationValidated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationValidated) Reset() {
	*x = ConfigurationValidated{}
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationValidated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationValidated) ProtoMessage() {}

func (x *ConfigurationValidated) ProtoReflect() protoreflect.Message {
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationValidated.ProtoReflect.Descriptor instead.
func (*ConfigurationValidated) Descriptor() ([]byte, []int) {
	return file_nodeplugin_v1_node_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigurationValidated) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ConfigurationValidated) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ConfigurationApplied struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationApplied) Reset() {
	*x = ConfigurationApplied{}
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationApplied) ProtoMessage() {}

func (x *ConfigurationApplied) ProtoReflect() protoreflect.Message {
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationApplied.ProtoReflect.Descriptor instead.
func (*ConfigurationApplied) Descriptor() ([]byte, []int) {
	return file_nodeplugin_v1_node_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigurationApplied) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ConfigurationApplied) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_nodeplugin_v1_node_plugin_proto_rawDescGZIP(), []int{5}
}

type GetStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Generation          uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	ConfigurationSha256 string                 `protobuf:"bytes,2,opt,name=configuration_sha256,json=configurationSha256,proto3" json:"configuration_sha256,omitempty"`
	Health              Health                 `protobuf:"varint,3,opt,name=health,proto3,enum=relayward.nodeplugin.v1.Health" json:"health,omitempty"`
	Message             string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeplugin_v1_node_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_nodeplugin_v1_node_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *GetStatusResponse) GetConfigurationSha256() string {
	if x != nil {
		return x.ConfigurationSha256
	}
	return ""
}

func (x *GetStatusResponse) GetHealth() Health {
	if x != nil {
		return x.Health
	}
	return Health_HEALTH_UNSPECIFIED
}

func (x *GetStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_nodeplugin_v1_node_plugin_proto protoreflect.FileDescriptor

const file_nodeplugin_v1_node_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1fnodeplugin/v1/node_plugin.proto\x12\x17relayward.nodeplugin.v1\"\x10\n" +
	"\x0eGetInfoRequest\"i\n" +
	"\x0fGetInfoResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"b\n" +
	"\x14ConfigurationRequest\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04json\x18\x03 \x01(\fR\x04json\"P\n" +
	"\x16ConfigurationValidated\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"N\n" +
	"\x14ConfigurationApplied\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"\x12\n" +
	"\x10GetStatusRequest\"\xb9\x01\n" +
	"\x11GetStatusResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x121\n" +
	"\x14configuration_sha256\x18\x02 \x01(\tR\x13configurationSha256\x127\n" +
	"\x06health\x18\x03 \x01(\x0e2\x1f.relayward.nodeplugin.v1.HealthR\x06health\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*_\n" +
	"\x06Health\x12\x16\n" +
	"\x12HEALTH_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHEALTH_STARTING\x10\x01\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x02\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x032\xbb\x03\n" +
	"\n" +
	"NodePlugin\x12\\\n" +
	"\aGetInfo\x12'.relayward.nodeplugin.v1.GetInfoRequest\x1a(.relayward.nodeplugin.v1.GetInfoResponse\x12w\n" +
	"\x15ValidateConfiguration\x12-.relayward.nodeplugin.v1.ConfigurationRequest\x1a/.relayward.nodeplugin.v1.ConfigurationValidated\x12r\n" +
	"\x12ApplyConfiguration\x12-.relayward.nodeplugin.v1.ConfigurationRequest\x1a-.relayward.nodeplugin.v1.ConfigurationApplied\x12b\n" +
	"\tGetStatus\x12).relayward.nodeplugin.v1.GetStatusRequest\x1a*.relayward.nodeplugin.v1.GetStatusResponseB?Z=github.com/Relayward/relayward-sdk/nodeplugin/v1;nodepluginv1b\x06proto3"

var (
	file_nodeplugin_v1_node_plugin_proto_rawDescOnce sync.Once
	file_nodeplugin_v1_node_plugin_proto_rawDescData []byte
)

func file_nodeplugin_v1_node_plugin_proto_rawDescGZIP() []byte {
	file_nodeplugin_v1_node_plugin_proto_rawDescOnce.Do(func() {
		file_nodeplugin_v1_node_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeplugin_v1_node_plugin_proto_rawDesc), len(file_nodeplugin_v1_node_plugin_proto_rawDesc)))
	})
	return file_nodeplugin_v1_node_plugin_proto_rawDescData
}

var file_nodeplugin_v1_node_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nodeplugin_v1_node_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_nodeplugin_v1_node_plugin_proto_goTypes = []any{
	(Health)(0),                    // 0: relayward.nodeplugin.v1.Health
	(*GetInfoRequest)(nil),         // 1: relayward.nodeplugin.v1.GetInfoRequest
	(*GetInfoResponse)(nil),        // 2: relayward.nodeplugin.v1.GetInfoResponse
	(*ConfigurationRequest)(nil),   // 3: relayward.nodeplugin.v1.ConfigurationRequest
	(*ConfigurationValidated)(nil), // 4: relayward.nodeplugin.v1.ConfigurationValidated
	(*ConfigurationApplied)(nil),   // 5: relayward.nodeplugin.v1.ConfigurationApplied
	(*GetStatusRequest)(nil),       // 6: relayward.nodeplugin.v1.GetStatusRequest
	(*GetStatusResponse)(nil),      // 7: relayward.nodeplugin.v1.GetStatusResponse
}
var file_nodeplugin_v1_node_plugin_proto_depIdxs = []int32{
	0, // 0: relayward.nodeplugin.v1.GetStatusResponse.health:type_name -> relayward.nodeplugin.v1.Health
	1, // 1: relayward.nodeplugin.v1.NodePlugin.GetInfo:input_type -> relayward.nodeplugin.v1.GetInfoRequest
	3, // 2: relayward.nodeplugin.v1.NodePlugin.ValidateConfiguration:input_type -> relayward.nodeplugin.v1.ConfigurationRequest
	3, // 3: relayward.nodeplugin.v1.NodePlugin.ApplyConfiguration:input_type -> relayward.nodeplugin.v1.ConfigurationRequest
	6, // 4: relayward.nodeplugin.v1.NodePlugin.GetStatus:input_type -> relayward.nodeplugin.v1.GetStatusRequest
	2, // 5: relayward.nodeplugin.v1.NodePlugin.GetInfo:output_type -> relayward.nodeplugin.v1.GetInfoResponse
	4, // 6: relayward.nodeplugin.v1.NodePlugin.ValidateConfiguration:output_type -> relayward.nodeplugin.v1.ConfigurationValidated
	5, // 7: relayward.nodeplugin.v1.NodePlugin.ApplyConfiguration:output_type -> relayward.nodeplugin.v1.ConfigurationApplied
	7, // 8: relayward.nodeplugin.v1.NodePlugin.GetStatus:output_type -> relayward.nodeplugin.v1.GetStatusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nodeplugin_v1_node_plugin_proto_init() }
func file_nodeplugin_v1_node_plugin_proto_init() {
	if File_nodeplugin_v1_node_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeplugin_v1_node_plugin_proto_rawDesc), len(file_nodeplugin_v1_node_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeplugin_v1_node_plugin_proto_goTypes,
		DependencyIndexes: file_nodeplugin_v1_node_plugin_proto_depIdxs,
		EnumInfos:         file_nodeplugin_v1_node_plugin_proto_enumTypes,
		MessageInfos:      file_nodeplugin_v1_node_plugin_proto_msgTypes,
	}.Build()
	File_nodeplugin_v1_node_plugin_proto = out.File
	file_nodeplugin_v1_node_plugin_proto_goTypes = nil
	file_nodeplugin_v1_node_plugin_proto_depIdxs = nil
}
