// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: nodeplugin/v1/node_plugin.proto

package nodepluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodePlugin_GetInfo_FullMethodName               = "/relayward.nodeplugin.v1.NodePlugin/GetInfo"
	NodePlugin_ValidateConfiguration_FullMethodName = "/relayward.nodeplugin.v1.NodePlugin/ValidateConfiguration"
	NodePlugin_ApplyConfiguration_FullMethodName    = "/relayward.nodeplugin.v1.NodePlugin/ApplyConfiguration"
	NodePlugin_GetStatus_FullMethodName             = "/relayward.nodeplugin.v1.NodePlugin/GetStatus"
)

// NodePluginClient is the client API for NodePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodePluginClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	ValidateConfiguration(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*ConfigurationValidated, error)
	ApplyConfiguration(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*ConfigurationApplied, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type nodePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewNodePluginClient(cc grpc.ClientConnInterface) NodePluginClient {
	return &nodePluginClient{cc}
}

func (c *nodePluginClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, NodePlugin_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodePluginClient) ValidateConfiguration(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*ConfigurationValidated, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigurationValidated)
	err := c.cc.Invoke(ctx, NodePlugin_ValidateConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodePluginClient) ApplyConfiguration(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*ConfigurationApplied, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigurationApplied)
	err := c.cc.Invoke(ctx, NodePlugin_ApplyConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodePluginClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, NodePlugin_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodePluginServer is the server API for NodePlugin service.
// All implementations must embed UnimplementedNodePluginServer
// for forward compatibility.
type NodePluginServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	ValidateConfiguration(context.Context, *ConfigurationRequest) (*ConfigurationValidated, error)
	ApplyConfiguration(context.Context, *ConfigurationRequest) (*ConfigurationApplied, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	mustEmbedUnimplementedNodePluginServer()
}

// UnimplementedNodePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodePluginServer struct{}

func (UnimplementedNodePluginServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedNodePluginServer) ValidateConfiguration(context.Context, *ConfigurationRequest) (*ConfigurationValidated, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateConfiguration not implemented")
}
func (UnimplementedNodePluginServer) ApplyConfiguration(context.Context, *ConfigurationRequest) (*ConfigurationApplied, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyConfiguration not implemented")
}
func (UnimplementedNodePluginServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedNodePluginServer) mustEmbedUnimplementedNodePluginServer() {}
func (UnimplementedNodePluginServer) testEmbeddedByValue()                    {}

// UnsafeNodePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodePluginServer will
// result in compilation errors.
type UnsafeNodePluginServer interface {
	mustEmbedUnimplementedNodePluginServer()
}

func RegisterNodePluginServer(s grpc.ServiceRegistrar, srv NodePluginServer) {
	// If the following call pancis, it indicates UnimplementedNodePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodePlugin_ServiceDesc, srv)
}

func _NodePlugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodePluginServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodePlugin_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodePluginServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodePlugin_ValidateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodePluginServer).ValidateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodePlugin_ValidateConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodePluginServer).ValidateConfiguration(ctx, req.(*ConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodePlugin_ApplyConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodePluginServer).ApplyConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodePlugin_ApplyConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodePluginServer).ApplyConfiguration(ctx, req.(*ConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodePlugin_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodePluginServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodePlugin_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodePluginServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodePlugin_ServiceDesc is the grpc.ServiceDesc for NodePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relayward.nodeplugin.v1.NodePlugin",
	HandlerType: (*NodePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _NodePlugin_GetInfo_Handler,
		},
		{
			MethodName: "ValidateConfiguration",
			Handler:    _NodePlugin_ValidateConfiguration_Handler,
		},
		{
			MethodName: "ApplyConfiguration",
			Handler:    _NodePlugin_ApplyConfiguration_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _NodePlugin_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodeplugin/v1/node_plugin.proto",
}
